### ISSUE TITLE
无法加载类？奇怪

### ISSUE THREAD

**Issue by Tokyo-Lei** [inhere/php-srouter#11]
atal error: Uncaught Error: Class 'Inhere\Route\Router' not found in J:\r\index.php:4 Stack trace: #0 {main} thrown in J:\r\index.php on line 4
----------------------------
index.php 
----------------------------
use Inhere\Route\Router;
$router = new Router();

print_r($router);

$router->get('/', function() {
echo 'hello';
});

----------------------------
php 7.3.4

**Comment by Tokyo-Lei** [comment]
<?php

use Inhere\Route\Router;
$router = new Router();


print_r($router);

$router->get('/', function() {
    echo 'hello';
});

**Comment by inhere** [comment]
需要先加载 autoload 文件。直接使用怎么找到类在哪里 :(

composer 安装一下包，然后在你这个文件加上：

```php
require __DIR__ . '/vendor/autoload.php';
```

**Comment by Tokyo-Lei** [comment]
抱歉，我没仔细检查！ 这回可以了~
