### ISSUE TITLE
不能写个新手教程吗?引入文件都不知道引入哪些文件各种报错 谢谢

### ISSUE THREAD

**Issue by AtlantisDe** [inhere/php-srouter#4]
require('static/Route/RouterInterface.php');
require('static/Route/SRouter.php');
require('static/Route/RouterConfigTrait.php');
require('static/Route/Router.php');

HP Fatal error:  Uncaught Error: Class 'Inhere\Route\Route' not found i

各种报错 新手难入手啊 说明文档能详细点吗?

**Comment by inhere** [comment]
😄  你不用composer 的吗？

> 使用composer,它会自动加载的。

`composer require inhere/sroute` 然后就可以:

```php
use Inhere\Route\Router;

$router = new Router();
```

> 不使用composer，则可以参考 `test/boot.php` 里的写法，手动注册。

https://github.com/inhere/php-srouter/blob/b869feb27e4d41db39ad3603e19a16768a4efe62/test/boot.php#L14-L33

**Comment by AtlantisDe** [comment]
composer 用了 
刚刚装好 但是 访问了 没输出 hello.
我刚刚研究这个php路由经验比较少 正在看你说明文档
```php
require __DIR__ . '/vendor/autoload.php';


use Inhere\Route\Router;

$router = new Router();
$router->get('/', function() {
    echo 'hello';
});

```

**Comment by inhere** [comment]
你这样只是注册了路由，没有开始调度处理。
你可以参考 examples 里面的使用。

**Comment by AtlantisDe** [comment]
## examples 这个你确认能完全运行么?
- 各种报错啊 看着好像入手不难 没调试成功就感觉好难啊 你这边有没一个简单的demo 的php文件让我运行就能跑起来我看看是啥效果的不?
```php
PHP Fatal error:  Uncaught Error: Class 'Swoole\Http\Server' not found in D:\Work\Seosite\Dev\www.aaa.com\example\swoole-server.php:49
Stack trace:
#0 {main}
  thrown in D:\Work\Seosite\Dev\www.aaa.com\example\swoole-server.php on line 49
```

**Comment by inhere** [comment]
😄  example里都是示例啊！

不过你选错了，这个是要swoole扩展的。

```bash
// 运行 example/object.php
php -S 127.0.0.1:5671 example/object.php

// 运行 example/static.php
php -S 127.0.0.1:5670 example/static.php
``

**Comment by AtlantisDe** [comment]
# 404报错啊
## 还有我想问下,composer里面
```php
\vendor\inhere\sroute
//这里都有一份srouter了 我还需要拷贝一份git到我网站根目录去么?
感觉这就重复了
如果不拷贝想example里面的文件运行就不行
会报错
刚刚这个运行到倒是能运行了 但是报错404

最后我想问下,如果服务器部署时候 没有装
composer 程序会不会跑不起来啊
新手问你这些问题太白痴了 我自己都觉得 但是没办法
刚刚入门

最后一个问题.
我想做 一个 比如访问首页 index.php?c=main
这样的路由 我想让它显示 比如 view/main.html这样的视图文件
是怎么写的哟
就想写个简单的.
然后刚刚了解这个路由知识还不知道咋入门.
谢谢哟....
```

**Comment by inhere** [comment]
我这只是个的路由库，是用来自己拼框架。你要做网站需要自定义好多东西的。

你要做网站还是建议直接用 yii ThinkPHP 之类框架，更容易用来开发功能。

**Comment by AtlantisDe** [comment]
是的我就用作路由而已
其它代码我都自己写的.
现在就路由这块比较生疏.

**Comment by inhere** [comment]
@AtlantisDe 摸索出来了吗 😄
